import { PHONE_APPS } from './js/apps/registry.js';
import { getRoles, buildPhoneRoleContext } from './js/phone/phone_context.js';
import { storage } from './js/phone/phone_storage.js';
import { requestAi, globalRules } from './js/phone/phone_api.js';
const root = document.querySelector('#app'); let currentRole = localStorage.getItem('currentPhoneContactId'); let currentApp = null;
const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c]));
const icon = (type) => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${{chat:'M4 5.5h16v10H9l-5 4v-14ZM8 10h8M8 13h5',gallery:'M4 5h16v14H4zM6 16l4-4 3 3 2-2 3 3M8 9h.1',wallet:'M4 7h16v11H4zM4 10h16M16 14h2',browser:'M4 5h16v14H4zM4 8h16M7 6.5h.1M10 6.5h.1',note:'M6 4h12v16H6zM9 9h6M9 12h6M9 15h4',spark:'M12 3c.7 5.6 3.5 8.4 9 9-5.5.6-8.3 3.4-9 9-.7-5.6-3.5-8.4-9-9 5.5-.6 8.3-3.4 9-9',settings:'M12 3v18M5 7h14M5 17h14'}}[type] || ''}"/></svg>`;
function toast(message) { const el = document.querySelector('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2300); }
function rolePicker() { root.innerHTML = `<section class="screen picker"><div class="luma">${icon('spark')}<span>Luma</span></div><span class="eyebrow">CHARACTER PHONE SYSTEM</span><h1>选择一位角色<br>进入手机</h1><p>每位角色拥有独立的 App 数据、记忆与生活轨迹。</p><div class="role-list">${getRoles().map((role) => `<button class="role" data-role="${role.id}"><i>${role.avatar}</i><span><b>${role.name}</b><small>${role.persona}</small></span><em>›</em></button>`).join('')}</div></section>`; document.querySelectorAll('[data-role]').forEach((button) => button.onclick = () => { currentRole = button.dataset.role; localStorage.setItem('currentPhoneContactId', currentRole); home(); }); }
function home() { const role = getRoles().find((entry) => entry.id === currentRole); root.innerHTML = `<section class="screen home"><header><button class="avatar" id="change-role">${role.avatar}</button><div><span>${new Date().toLocaleDateString('zh-CN', { month:'long', day:'numeric', weekday:'short' })}</span><b>下午好，${role.name}</b></div><button class="settings" id="settings">${icon('settings')}</button></header><div class="orb"></div><section class="headline"><span class="eyebrow">PERSONAL SPACE</span><h1>你的生活，<br><i>正在发生。</i></h1></section><div class="app-grid">${Object.values(PHONE_APPS).map((app) => `<button class="app-tile" data-app="${app.id}"><span class="app-icon ${app.id}">${icon(app.icon)}</span><b>${app.name}</b><small>${app.getCount(storage.appData(currentRole, app.id))} 条记录</small></button>`).join('')}</div><button class="generate-all" id="generate-all">${icon('spark')} 整机刷新</button></section>`; document.querySelector('#change-role').onclick = rolePicker; document.querySelector('#settings').onclick = settings; document.querySelectorAll('[data-app]').forEach((button) => button.onclick = () => appView(button.dataset.app)); document.querySelector('#generate-all').onclick = generateAll; }
function appView(id) { currentApp = PHONE_APPS[id]; const data = storage.appData(currentRole, id); root.innerHTML = `<section class="screen app-screen"><header class="simple-header"><button id="back">‹</button><div><span class="app-icon ${id}">${icon(currentApp.icon)}</span><b>${currentApp.name}</b></div><button id="refresh">${icon('spark')}</button></header><div class="app-intro"><span class="eyebrow">${currentApp.description.toUpperCase()}</span><h1>${currentApp.name}</h1><p>与角色状态同步的个人数据</p></div><div class="records" id="records">${currentApp.renderList(data)}</div></section>`; document.querySelector('#back').onclick = home; document.querySelector('#refresh').onclick = () => generateOne(id); document.querySelectorAll('[data-detail]').forEach((button) => button.onclick = () => detailView(id, button.dataset.detail)); }
function detailView(id, index) { const app = PHONE_APPS[id], data = storage.appData(currentRole, id); root.innerHTML = `<section class="screen app-screen"><header class="simple-header"><button id="back">‹</button><div><b>${app.name}</b></div></header>${app.renderDetail(data, index)}</section>`; document.querySelector('#back').onclick = () => appView(id); }
async function generateOne(id) { const app = PHONE_APPS[id]; root.classList.add('loading'); try { const prompt = storage.prompt(id) || app.prompt; const data = await requestAi({ context: buildPhoneRoleContext(currentRole, id), prompt: `${globalRules}\n${prompt}`, app }); storage.setAppData(currentRole, id, data); appView(id); toast(`${app.name} 已更新`); } catch (error) { toast(error.message); } finally { root.classList.remove('loading'); } }
async function generateAll() { root.classList.add('loading'); for (const id of Object.keys(PHONE_APPS)) await generateOne(id); root.classList.remove('loading'); home(); toast('整部手机已同步更新'); }
function settings() { root.innerHTML = `<section class="screen app-screen"><header class="simple-header"><button id="back">‹</button><div><b>系统设置</b></div></header><div class="app-intro"><span class="eyebrow">PHONE ENGINE</span><h1>数据与提示词</h1><p>所有 App 共享角色上下文和事件线。</p></div><div class="settings-list">${Object.values(PHONE_APPS).map((app) => `<button class="record" data-prompt="${app.id}"><span><b>${app.name} 提示词</b><small>单独修改并保存</small></span><em>›</em></button>`).join('')}</div></section>`; document.querySelector('#back').onclick = home; document.querySelectorAll('[data-prompt]').forEach((button) => button.onclick = () => promptEditor(button.dataset.prompt)); }
function promptEditor(id) { const app = PHONE_APPS[id]; root.innerHTML = `<section class="screen app-screen"><header class="simple-header"><button id="back">‹</button><div><b>${app.name} 提示词</b></div></header><div class="editor"><span class="eyebrow">APP PROMPT</span><textarea id="prompt">${esc(storage.prompt(id) || app.prompt)}</textarea><button class="generate-all" id="save">保存提示词</button></div></section>`; document.querySelector('#back').onclick = settings; document.querySelector('#save').onclick = () => { storage.setPrompt(id, document.querySelector('#prompt').value); toast('提示词已保存'); settings(); }; }
currentRole ? home() : rolePicker();
